---

################################
# APPDATA
################################

- name: Create znc appdata directory
  ansible.builtin.file:
    path: '{{ znc_paths_location }}'
    state: directory
    owner: '{{ znc_env_puid }}'
    group: '{{ znc_env_pgid }}'
    mode: '0755'

- name: Create znc config directory
  ansible.builtin.file:
    path: '{{ znc_paths_location }}/config'
    state: directory
    owner: '{{ znc_env_puid }}'
    group: '{{ znc_env_pgid }}'
    mode: '0755'

################################
# CONTAINER
################################

- name: Create ZNC container
  when: not toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ znc_basics_name }}'
    image: '{{ znc_basics_image_repo }}:{{ znc_basics_image_tag }}'
    networks: '{{ znc_networks }}'
    env:
      PUID: '{{ znc_env_puid }}'
      PGID: '{{ znc_env_pgid }}'
      TZ: '{{ timezone }}'
    ports:
      - '{{ znc_ports_web_host }}:{{ znc_ports_web_cont }}'
      - '{{ znc_ports_irc_host }}:{{ znc_ports_irc_cont }}'
    volumes: '{{ znc_binds_config_mapping }}'
    restart_policy: '{{ znc_basics_restart_policy }}'

- name: Create ZNC traefik container
  when: toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ znc_basics_name }}'
    image: '{{ znc_basics_image_repo }}:{{ znc_basics_image_tag }}'
    networks: '{{ znc_networks }}'
    env:
      PUID: '{{ znc_env_puid }}'
      PGID: '{{ znc_env_pgid }}'
      TZ: '{{ timezone }}'
    labels: '{{ znc_labels }}'
    ports:
      - '{{ znc_ports_web_host }}:{{ znc_ports_web_cont }}'
      - '{{ znc_ports_irc_host }}:{{ znc_ports_irc_cont }}'     
    volumes: '{{ znc_binds_config_mapping }}'
    restart_policy: '{{ znc_basics_restart_policy }}'