---

- name: Ping for existing main database
  community.postgresql.postgresql_ping:
    login_host: '{{ postgres_basics_host }}'
    login_user: '{{ postgres_auth_user }}'
    login_password: '{{ postgres_auth_password }}'
    port: '{{ postgres_ports_host }}'
    db: '{{ autobrr_postgres_database }}'
  register: autobrr_postgres_db

- name: Create postgres main database
  when: not autobrr_postgres_db == true
  community.postgresql.postgresql_db:
    login_host: '{{ postgres_basics_host }}'
    login_user: '{{ postgres_auth_user }}'
    login_password: '{{ postgres_auth_password }}'
    port: '{{ postgres_ports_host }}'
    name: '{{ autobrr_postgres_database }}'
    state: present