---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ thelounge_cloudflare_api_token }}'
    zone: '{{ thelounge_traefik_domain }}'
    state: absent
    type: CNAME
    record: '{{ thelounge_traefik_subdomain }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ thelounge_cloudflare_api_token }}'
    zone: '{{ thelounge_traefik_domain }}'
    state: absent
    type: A
    record: '{{ thelounge_traefik_subdomain }}'

- name: Add DNS record
  community.general.cloudflare_dns:
    api_token: '{{ thelounge_cloudflare_api_token }}'
    zone: '{{ thelounge_traefik_domain }}'
    state: present
    solo: true
    proxied: '{{ thelounge_cloudflare_proxy }}'
    type: '{{ thelounge_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ thelounge_traefik_subdomain }}'
  register: thelounge_cloudflare_record_creation_status

- name: Tasks on success
  when: thelounge_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        thelounge_cloudflare_record_print: '{{ (thelounge_traefik_subdomain == thelounge_traefik_domain) | ternary(thelounge_traefik_domain, thelounge_traefik_subdomain + "." + thelounge_traefik_domain) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ thelounge_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ thelounge_cloudflare_proxy }}'