---

################################
# CLEAN UP
################################

- name: Register thelounge container
  community.docker.docker_container_info:
    name: '{{ thelounge_basics_name }}'
  register: thelounge_existing_container_result

- name: Remove existing thelounge container
  when: thelounge_existing_container_result.exists
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ thelounge_basics_name }}'
    state: absent
    stop_timeout: 10
  register: remove_thelounge_docker
  retries: 5
  delay: 10
  until: remove_thelounge_docker is succeeded

################################
# APPDATA
################################

- name: Create thelounge appdata directory
  ansible.builtin.file:
    path: '{{ thelounge_paths_location }}'
    state: directory
    owner: '{{ thelounge_env_puid }}'
    group: '{{ thelounge_env_pgid }}'
    mode: '0755'

- name: Create thelounge config directory
  ansible.builtin.file:
    path: '{{ thelounge_paths_location }}/config'
    state: directory
    owner: '{{ thelounge_env_puid }}'
    group: '{{ thelounge_env_pgid }}'
    mode: '0755'

################################
# CONTAINER
################################

- name: Create thelounge container
  when: not toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ thelounge_basics_name }}'
    image: '{{ thelounge_basics_image_repo }}:{{ thelounge_basics_image_tag }}'
    networks: '{{ thelounge_networks }}'
    env:
      PUID: '{{ thelounge_env_puid }}'
      PGID: '{{ thelounge_env_pgid }}'
      TZ: '{{ timezone }}'
    ports:
      - '{{ thelounge_ports_host }}:{{ thelounge_ports_cont }}'
    volumes: '{{ thelounge_binds_config_mapping }}'
    restart_policy: '{{ thelounge_basics_restart_policy }}'

- name: Create thelounge traefik container
  when: toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ thelounge_basics_name }}'
    image: '{{ thelounge_basics_image_repo }}:{{ thelounge_basics_image_tag }}'
    networks: '{{ thelounge_networks }}'
    env:
      PUID: '{{ thelounge_env_puid }}'
      PGID: '{{ thelounge_env_pgid }}'
      TZ: '{{ timezone }}'
    labels: '{{ thelounge_labels }}'
    ports:
      - '{{ thelounge_ports_host }}:{{ thelounge_ports_cont }}'
    volumes: '{{ thelounge_binds_config_mapping }}'
    restart_policy: '{{ thelounge_basics_restart_policy }}'