---

################################
# DOMAIN
################################

  ## autobrr
autobrr_traefik_subdomain: '{{ autobrr_basics_name }}'
autobrr_traefik_domain: ''
autobrr_traefik_port: '{{ autobrr_ports_cont }}'

  ## thelounge
thelounge_traefik_subdomain: '{{ thelounge_basics_name }}'
thelounge_traefik_domain: '{{ autobrr_traefik_domain }}'
thelounge_traefik_port: '{{ thelounge_ports_cont }}'

  ## znc
znc_traefik_subdomain: '{{ znc_basics_name }}'
znc_traefik_domain: '{{ autobrr_traefik_domain }}'
znc_traefik_web_port: '{{ znc_ports_web_cont }}'
znc_traefik_irc_port: '{{ znc_ports_irc_cont }}'

################################
# NETWORK
################################

traefik_network: 'traefik_proxy'
traefik_network_driver: 'bridge'  ## only required if network doesn't exist
traefik_network_subnet: ''  ## only required if network doesn't exist

################################
# TLS
################################

traefik_tls_certresolver: 'dns-cloudflare'
traefik_tls_options: 'tls-opts@file'

################################
# ROUTER (HTTP)
################################

  ## autobrr
autobrr_traefik_http_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
autobrr_traefik_http_rule: 'Host(`{{ autobrr_traefik_subdomain }}.{{ autobrr_traefik_domain }}`)'
autobrr_traefik_http_priority: '20'

autobrr_traefik_http_api_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
autobrr_traefik_http_api_rule: '{{ autobrr_traefik_http_rule + " && (PathPrefix(`/api`))" }}'
autobrr_traefik_http_api_priority: '30'

  ## thelounge
thelounge_traefik_http_middlewares: '{{ autobrr_traefik_http_middlewares }}'
thelounge_traefik_http_rule: 'Host(`{{ thelounge_traefik_subdomain }}.{{ thelounge_traefik_domain }}`)'
thelounge_traefik_http_priority: '{{ autobrr_traefik_http_priority }}'

thelounge_traefik_http_api_middlewares: '{{ autobrr_traefik_http_api_middlewares }}'
thelounge_traefik_http_api_rule: '{{ thelounge_traefik_http_rule + " && (PathPrefix(`/uploads`))" }}'
thelounge_traefik_http_api_priority: '{{ autobrr_traefik_http_api_priority }}'

  ## znc
znc_traefik_http_web_middlewares: '{{ autobrr_traefik_http_middlewares }}'
znc_traefik_http_web_rule: 'Host(`{{ znc_traefik_subdomain }}.{{ znc_traefik_domain }}`)'
znc_traefik_http_web_priority: '{{ autobrr_traefik_http_priority }}'

znc_traefik_http_web_api_middlewares: '{{ autobrr_traefik_http_api_middlewares }}'
znc_traefik_http_web_api_rule: '{{ znc_traefik_http_web_rule + " && (PathPrefix(`/uploads`))" }}'
znc_traefik_http_web_api_priority: '{{ autobrr_traefik_http_api_priority }}'

################################
# ROUTER (HTTPS)
################################

  ## autobrr
autobrr_traefik_https_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
autobrr_traefik_https_rule: 'Host(`{{ autobrr_traefik_subdomain }}.{{ autobrr_traefik_domain }}`)'
autobrr_traefik_https_priority: '20'

autobrr_traefik_https_api_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
autobrr_traefik_https_api_rule: '{{ autobrr_traefik_https_rule + " && (PathPrefix(`/api`))" }}'
autobrr_traefik_https_api_priority: '30'

  ## thelounge
thelounge_traefik_https_middlewares: '{{ autobrr_traefik_https_middlewares }}'
thelounge_traefik_https_rule: 'Host(`{{ thelounge_traefik_subdomain }}.{{ thelounge_traefik_domain }}`)'
thelounge_traefik_https_priority: '{{ autobrr_traefik_https_priority }}'

thelounge_traefik_https_api_middlewares: '{{ autobrr_traefik_https_api_middlewares }}'
thelounge_traefik_https_api_rule: '{{ thelounge_traefik_https_rule + " && (PathPrefix(`/uploads`))" }}'
thelounge_traefik_https_api_priority: '{{ autobrr_traefik_https_api_priority }}'

  ## znc
znc_traefik_https_web_middlewares: '{{ autobrr_traefik_https_middlewares }}'
znc_traefik_https_web_rule: 'Host(`{{ znc_traefik_subdomain }}.{{ znc_traefik_domain }}`)'
znc_traefik_https_web_priority: '{{ autobrr_traefik_https_priority }}'

znc_traefik_https_web_api_middlewares: '{{ autobrr_traefik_https_api_middlewares }}'
znc_traefik_https_web_api_rule: '{{ znc_traefik_https_web_rule + " && (PathPrefix(`/uploads`))" }}'
znc_traefik_https_web_api_priority: '{{ autobrr_traefik_https_api_priority }}'

################################
# ROUTER (TCP)
################################

  ## znc-irc
znc_traefik_tcp_irc_rule: 'HostSNI(`{{ znc_traefik_subdomain }}.{{ znc_traefik_domain }}`)'
znc_traefik_tcp_irc_priority: '{{ autobrr_traefik_http_priority }}'

################################
# THEME-PARK
################################

autobrr_traefik_themepark_theme: 'hotpink'
