---

################################
# DOMAIN
################################

  ## autobrr
autobrr_traefik_subdomain: '{{ autobrr_basics_name }}'
autobrr_traefik_domain: ''
autobrr_traefik_port: '{{ autobrr_ports_cont }}'

  ## thelounge
autobrr_thelounge_traefik_subdomain: '{{ autobrr_thelounge_basics_name }}'
autobrr_thelounge_traefik_domain: '{{ autobrr_traefik_domain }}'
autobrr_thelounge_traefik_port: '{{ autobrr_thelounge_ports_cont }}'

  ## znc
autobrr_znc_traefik_subdomain: '{{ autobrr_znc_basics_name }}'
autobrr_znc_traefik_domain: '{{ autobrr_traefik_domain }}'
autobrr_znc_traefik_port: '{{ autobrr_znc_ports_cont }}'

################################
# NETWORK
################################

autobrr_traefik_network: 'traefik_proxy'
autobrr_traefik_network_driver: 'bridge'  ## only required if network doesn't exist
autobrr_traefik_network_subnet: ''  ## only required if network doesn't exist

################################
# TLS
################################

autobrr_traefik_tls_certresolver: 'dns-cloudflare'
autobrr_traefik_tls_options: 'tls-opts@file'

################################
# ROUTER (HTTP)
################################

  ## autobrr
autobrr_traefik_http_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
autobrr_traefik_http_rule: 'Host(`{{ autobrr_traefik_subdomain }}.{{ autobrr_traefik_domain }}`)'
autobrr_traefik_http_priority: '20'

autobrr_traefik_http_api_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
autobrr_traefik_http_api_rule: '{{ autobrr_traefik_http_rule + " && (PathPrefix(`/api`))" }}'
autobrr_traefik_http_api_priority: '30'

  ## thelounge
autobrr_thelounge_traefik_http_middlewares: '{{ autobrr_traefik_http_middlewares }}'
autobrr_thelounge_traefik_http_rule: 'Host(`{{ autobrr_thelounge_traefik_subdomain }}.{{ autobrr_thelounge_traefik_domain }}`)'
autobrr_thelounge_traefik_http_priority: '{{ autobrr_traefik_http_priority }}'

autobrr_thelounge_traefik_http_api_middlewares: '{{ autobrr_traefik_http_api_middlewares }}'
autobrr_thelounge_traefik_http_api_rule: '{{ autobrr_thelounge_traefik_http_rule + " && (PathPrefix(`/uploads`))" }}'
autobrr_thelounge_traefik_http_api_priority: '{{ autobrr_traefik_http_api_priority }}'

  ## znc
autobrr_znc_traefik_http_middlewares: '{{ autobrr_traefik_http_middlewares }}'
autobrr_znc_traefik_http_rule: 'Host(`{{ autobrr_znc_traefik_subdomain }}.{{ autobrr_znc_traefik_domain }}`)'
autobrr_znc_traefik_http_priority: '{{ autobrr_traefik_http_priority }}'

autobrr_znc_traefik_http_api_middlewares: '{{ autobrr_traefik_http_api_middlewares }}'
autobrr_znc_traefik_http_api_rule: '{{ autobrr_znc_traefik_http_rule + " && (PathPrefix(`/uploads`))" }}'
autobrr_znc_traefik_http_api_priority: '{{ autobrr_traefik_http_api_priority }}'

################################
# ROUTER (HTTPS)
################################

  ## autobrr
autobrr_traefik_https_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
autobrr_traefik_https_rule: 'Host(`{{ autobrr_traefik_subdomain }}.{{ autobrr_traefik_domain }}`)'
autobrr_traefik_https_priority: '20'

autobrr_traefik_https_api_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
autobrr_traefik_https_api_rule: '{{ autobrr_traefik_https_rule + " && (PathPrefix(`/api`))" }}'
autobrr_traefik_https_api_priority: '30'

  ## thelounge
autobrr_thelounge_traefik_https_middlewares: '{{ autobrr_traefik_https_middlewares }}'
autobrr_thelounge_traefik_https_rule: 'Host(`{{ autobrr_thelounge_traefik_subdomain }}.{{ autobrr_thelounge_traefik_domain }}`)'
autobrr_thelounge_traefik_https_priority: '{{ autobrr_traefik_https_priority }}'

autobrr_thelounge_traefik_https_api_middlewares: '{{ autobrr_traefik_https_api_middlewares }}'
autobrr_thelounge_traefik_https_api_rule: '{{ autobrr_thelounge_traefik_https_rule + " && (PathPrefix(`/uploads`))" }}'
autobrr_thelounge_traefik_https_api_priority: '{{ autobrr_traefik_https_api_priority }}'

  ## znc
autobrr_znc_traefik_https_middlewares: '{{ autobrr_traefik_https_middlewares }}'
autobrr_znc_traefik_https_rule: 'Host(`{{ autobrr_znc_traefik_subdomain }}.{{ autobrr_znc_traefik_domain }}`)'
autobrr_znc_traefik_https_priority: '{{ autobrr_traefik_https_priority }}'

autobrr_znc_traefik_https_api_middlewares: '{{ autobrr_traefik_https_api_middlewares }}'
autobrr_znc_traefik_https_api_rule: '{{ autobrr_znc_traefik_https_rule + " && (PathPrefix(`/uploads`))" }}'
autobrr_znc_traefik_https_api_priority: '{{ autobrr_traefik_https_api_priority }}'

################################
# THEME-PARK
################################

autobrr_traefik_themepark_theme: 'hotpink'
