---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ autobrr_cloudflare_api_token }}'
    zone: '{{ autobrr_traefik_domain }}'
    state: absent
    type: CNAME
    record: '{{ autobrr_traefik_subdomain }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ autobrr_cloudflare_api_token }}'
    zone: '{{ autobrr_traefik_domain }}'
    state: absent
    type: A
    record: '{{ autobrr_traefik_subdomain }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add DNS record
  community.general.cloudflare_dns:
    api_token: '{{ autobrr_cloudflare_api_token }}'
    zone: '{{ autobrr_traefik_domain }}'
    state: present
    solo: true
    proxied: '{{ autobrr_cloudflare_proxy }}'
    type: '{{ autobrr_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}' 
    record: '{{ autobrr_traefik_subdomain }}'
  register: autobrr_cloudflare_record_creation_status

- name: Tasks on success
  when: autobrr_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        autobrr_cloudflare_record_print: '{{ (autobrr_traefik_subdomain == autobrr_traefik_domain) | ternary(autobrr_traefik_domain, autobrr_traefik_subdomain + "." + autobrr_traefik_domain) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ autobrr_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ autobrr_cloudflare_proxy }}'
